version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-for-flashcards-api-yzeng33
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
